####
# Created from:
# https://github.com/docker/build-push-action
# https://docs.docker.com/ci-cd/github-actions/
####
# Took this from your samples to build Dr. Duncan
# GitHub Actions workflow name
name: Docker-Login-Build-Push
# event trigger(s)
on:
  # triggers only on pushes to main branch
  push:
    branches: [main]
# variables used in this workflow
env:
  # variable holding my repo folder name (using DockerHub is assumed)
  DOCKER_HUB_REPO: project4
# jobs - each jobs runs on a runner - parralel by deafult, can be dependent based on id
#     https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobs
jobs:
  build_and_push:
    name: Build docker image and push to Docker Hub
    # OS of runner
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - 
        name: Checkout repo
        uses: actions/checkout@v3
      # Login in to DockerHub, credentials stored as GitHub repository secrets
      #    Usage documentation: https://github.com/marketplace/actions/docker-login
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # v2 allows use of buildx, requires separate use of docker-login action
      #    total list of updates between v1 & v2: https://github.com/docker/build-push-action/blob/master/UPGRADE.md
      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context:  .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/project4:latest
          # Example getting fancy with tags: 
          #   https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
