####
# Created from:
# https://github.com/docker/build-push-action
# https://docs.docker.com/ci-cd/github-actions/
# Took this from your samples to build Dr. Duncan
####

# GitHub Actions workflow name
name: Docker-Login-Build-Push

# Event trigger(s)
on:
  # Triggers only on pushes to main branch
  push:
    branches: [main]

# Variables used in this workflow
env:
  # Variable holding my DockerHub repository name
  DOCKER_HUB_REPO: project4

# Jobs - each job runs on a runner
# Can run in parallel by default, or be dependent on other jobs
jobs:
  build_and_push:
    name: Build Docker image and push to Docker Hub
    # OS of runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo contents to the runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Login to DockerHub
      # Credentials stored as GitHub repository secrets
      # Usage documentation: https://github.com/marketplace/actions/docker-login
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 3: Build and push Docker image
      # Using official docker/build-push-action v5
      # Docs: https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .                 # The Build context is the repo root/using context found in: https://docs.github.com/en/actions/reference/workflows-and-actions/contexts
          push: true                 # Pushing image to DockerHub
          tags: ${{ secrets.DOCKER_USERNAME }}/project4:latest
          # Example for advanced tags: see https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
